### ISSUE TITLE
Simple Notification Service (SNS), missing sqs endpoint on command

### ISSUE THREAD

**Issue by Nikola-Milovic** [localstack/docs#1008]
In Working with[ SQS subscriptions with SNS](https://docs.localstack.cloud/user-guide/aws/sns/#working-with-sqs-subscriptions-for-sns) section, the command example

`awslocal receive-message --queue-url "http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/my-queue"`

Is missing the `sqs` endpoint, it should be 

`awslocal *sqs* receive-message --queue-url "http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/my-queue"`

Tiny issue, but easily amendable

**Comment by sannya-singal** [comment]
Hi @Nikola-Milovic, thanks for reporting this issue. We have fixed this in our [documentation](https://github.com/localstack/docs/pull/1011).
