### ISSUE TITLE
How do I get the AMI for CentOS

### ISSUE THREAD

**Issue by bgadicha1** [localstack/docs#1084]
While bringing up the EC2 instance, how do I know which AMI I need to use? I want to have CentOS 7.7 installed on my EC2 instance. Is there a publicly available AMI? I used CentOS website and tried to use their publicly available AMI ID while bringing up the EC2 instance. But an error comes up "The image id 'ami-0aedf6b1cb669b4c7' does not exist".

**Comment by MarcelStranak** [comment]
Hi @bgadicha1,

The details for using custom docker image are mentioned under https://docs.localstack.cloud/user-guide/aws/elastic-compute-cloud/#instances-and-amis.

> You can mark any Docker base image as AMI using the below command:
>`docker tag ubuntu:focal localstack-ec2/ubuntu-focal-ami:ami-000001`
>
>
>The above example will make LocalStack treat the ubuntu:focal Docker image as an AMI with name ubuntu-focal-ami and ID ami-000001.

You can test it with similar command `aws ec2 run-instances --image-id ami-000001 --count 1 --instance-type t3.nano`

**Comment by bgadicha1** [comment]
thanks this helped.
