### ISSUE TITLE
Unable to connect to docdb instance

### ISSUE THREAD

**Issue by bgadicha1** [localstack/docs#1107]
I brought up an EC2 instance and then a Docdb cluster and instance. Then I am trying to connect to Docdb cluster after logging into ec2 instance. This is the documentation that I followed.

https://docs.localstack.cloud/user-guide/aws/docdb/
(instead of mongosh, i am using mongo utility)

when I give the command
mongo mongodb://localhost:58231  or  mongo mongodb://localhost.localstack.cloud:58231 
it gives error
connecting to: mongodb://localhost:58231/?compressors=disabled&gssapiServiceName=mongodb
Error: couldn't connect to server localhost:58231, connection attempt failed: SocketException: Error connecting to localhost:58231 (127.0.0.1:58231) :: caused by :: Connection refused :

When i try this

mongo docdb://localhost.localstack.cloud:58231

it throws error like below

MongoDB shell version v3.6.8
exception: Must specify set name for replica set ConnectionStrings
 

I have one Docdb cluster and one instance. This is the result of describing the cluster.

{
    "DBClusters": [
        {
            "DBClusterIdentifier": "test-docdb-cluster",
            "DBClusterParameterGroup": "default.docdb",
            "Status": "available",
            "Endpoint": "localhost.localstack.cloud",
            "ReaderEndpoint": "localhost.localstack.cloud",
            "MultiAZ": false,
            "Engine": "docdb",
            "Port": 58231,
            "MasterUsername": "test",
            "DBClusterMembers": [
                {
                    "DBInstanceIdentifier": "test-company",
                    "IsClusterWriter": true,
                    "DBClusterParameterGroupStatus": "in-sync",
                    "PromotionTier": 1
                }
            ],
            "VpcSecurityGroups": [
                {
                    "VpcSecurityGroupId": "sg-4bf0c1b736965e905",
                    "Status": "active"
                }
            ],
            "StorageEncrypted": false,
            "DbClusterResourceId": "cluster-3297f80e",
            "DBClusterArn": "arn:aws:rds:us-east-1:000000000000:cluster:test-docdb-cluster"
        }
    ]
}

And in my local docker mongo container, i see this
	],
	"State": {
		"Status": "running",
		"Running": true,
		"Paused": false,
		"Restarting": false,
		"OOMKilled": false,
		"Dead": false,
		"Pid": 95053,
		"ExitCode": 0,
		"Error": "",
		"StartedAt": "2024-02-29T18:35:14.788714783Z",
		"FinishedAt": "0001-01-01T00:00:00Z"

Not sure what is missing here.

**Comment by bgadicha1** [comment]
This is the documentation that i followed.
https://docs.localstack.cloud/user-guide/aws/docdb/
(instead of mongosh, i am using mongo utility)

**Comment by bgadicha1** [comment]
Adding more info. I am trying to connect to mongodb from an ec2 instance. I could see both ec2 and mongodb containers. Just thought of giving this info.

**Comment by bgadicha1** [comment]
any updates please?

**Comment by MarcelStranak** [comment]
Hi @bgadicha1,

Please try using the same configuration as mentioned in docs:

> Connect to DocumentDB using Node.js Lambda
Important
You need to set DOCDB_PROXY_CONTAINER=1 when starting LocalStack to be able to use the returned Endpoint, which will be correctly resolved automatically.

> The flag DOCDB_PROXY_CONTAINER=1 changes the default behavior and the container will be started as proxied container. Meaning a port from the [pre-defined port](https://docs.localstack.cloud/references/external-ports/) range will be chosen, and when using lambda, you can use localhost.localstack.cloud to connect to the instance.

As well, please have a look at the [network troubleshooting](https://docs.localstack.cloud/references/network-troubleshooting/).
