### ISSUE TITLE
Docs on DocumentDB

### ISSUE THREAD

**Issue by kelvin-thinkbean** [localstack/docs#111]
I just signed up for LocalStack Pro and I am currently trying to use the DocumentDB service but I am finding it a bit hard since there  is no documentation (at least that I can find) on how to set this up and use it.

Are there any docs? Maybe there are Pro specific docs that I have been unable to find?

**Comment by ankitagit11** [comment]
I want to work on this issue. Please assign it to me.

**Comment by alexrashed** [comment]
Sorry for the late response. By now, we already have a dedicated page on DocumentDB: https://docs.localstack.cloud/user-guide/aws/docdb/
I'll close this issue, but please always feel free to submit PRs.
