### ISSUE TITLE
S3 Resource Browser

### ISSUE THREAD

**Issue by fredericoechaves** [localstack/docs#1111]
The "LocalStack Web Application" is deprecated and no longer maintained.

On the S3 documentations it would be nice to have a warning making it clear that the Resource Browser is no longer maintained. (https://docs.localstack.cloud/user-guide/aws/s3/#resource-browser)

**Comment by HarshCasper** [comment]
Hi — The LocalStack Web Application (app.localstack.cloud) isn't deprecated and is being actively maintained. You might confuse the Web Application with a local UI client that we used to ship with our pre-v1 Docker images. I don't think we should put any warning or deprecation notice, hence closing the issue :)
