### ISSUE TITLE
SNS SMS message retrospection

### ISSUE THREAD

**Issue by julian-amplica** [localstack/docs#1246]
PR https://github.com/localstack/localstack/pull/8667 added support for retrospection of SMS messages published via SNS at the `/_aws/sns/sms-messages` endpoint, but this feature is not documented on the [SNS page](https://docs.localstack.cloud/user-guide/aws/sns/).

**Comment by julian-amplica** [comment]
@bentsku Thank you! 🙏

**Comment by bentsku** [comment]
Sorry for the delay on that one, it took quite a long time 😅 feel free if you have any feedback! And thanks a lot for opening the issue 🙏
