### ISSUE TITLE
`/contributing/parity-testing` not found, linked to by "snapshot parity testing" on coverage page

### ISSUE THREAD

**Issue by huonw** [localstack/docs#1463]
On each coverage page, there seems to two explanations of what "Snapshot tested" means. These both link to https://docs.localstack.cloud/contributing/parity-testing/ and that is now a dead-link/"not found" page.

![image](https://github.com/user-attachments/assets/c94963e0-fe7b-48dd-a928-1e34d62b93f7)

For example https://docs.localstack.cloud/references/coverage/coverage_appsync/#terminology

> Snapshot Tested: the operation is part of a [snapshot parity test](https://docs.localstack.cloud/contributing/parity-testing/), which verifies the responses by LocalStack and AWS are the same
> ...
> Snapshot Tested this is a [snapshot parity test](https://docs.localstack.cloud/contributing/parity-testing/), meaning the responses are validated against AWS

https://github.com/localstack/docs/blob/0f246cd5f5325fad6fc13722d16c951afcc5c375/layouts/partials/coverage/coverage_table.html#L37

https://github.com/localstack/docs/blob/0f246cd5f5325fad6fc13722d16c951afcc5c375/layouts/partials/coverage/coverage_details.html#L19

**Comment by MarcelStranak** [comment]
For now, the article can be found at https://github.com/localstack/localstack/blob/master/docs/testing/parity-testing/README.md
