### ISSUE TITLE
Add (Pro) qualifier to IAM listing in feature coverage

### ISSUE THREAD

**Issue by ThomasQuinnKelly** [localstack/docs#171]
https://github.com/localstack/docs/blob/ae7512e61f7744bfd52c6bef26114a16048f3142/content/en/aws/feature-coverage.md?plain=1#L357

This line currently doesn't have the (Pro) suffix. Although if you click into the page "[IAM](https://docs.localstack.cloud/aws/iam/)" we do see the [LocalStack Pro](https://docs.localstack.cloud/categories/localstack-pro/) category.

Additionally this PR comment confirmed IAM is pro to me, a fact which eluded me before: https://github.com/localstack/localstack/issues/5688

**Comment by steffyP** [comment]
Hi @ThomasQuinnKelly, 

we actually do support some features for `iam` in the community version. Some additional features are only available in Pro, as you already pointed out.
In the community repo, you can find e.g. some use cases that work when checking the [provider](https://github.com/localstack/localstack/blob/master/localstack/services/iam/provider.py), or the [related tests](https://github.com/localstack/localstack/blob/master/tests/integration/test_iam.py).

In the overview we currently mark services with *Pro* if they only work in Pro and are not available in the community version.
