### ISSUE TITLE
update aws-go-sdk-v2 example on how to set endpoints

### ISSUE THREAD

**Issue by thrau** [localstack/docs#212]
* https://docs.localstack.cloud/integrations/sdks/go/
* see issue description here: https://github.com/localstack/localstack/issues/6467

**Comment by HarshCasper** [comment]
We have our updated docs here — https://docs.localstack.cloud/user-guide/integrations/sdks/go/

**Comment by focusaurus** [comment]
The updated docs use `EndpointResolverWithOptionsFunc` which is deprecated as of aws-sdk-go-v2 v1.27.1. Did this API go through another round of deprecation so soon?
