### ISSUE TITLE
Add docs for Lambda custom image 

### ISSUE THREAD

**Issue by MarcelStranak** [localstack/docs#247]
Bash and python are required to be installed on the custom docker image. Otherwise, it will fail with an error `exec /tmp/xxx.sh: no such file or directory`

Info:
Slack: support_jason991_u03tf9r8201
Notion: Custom-lambda-docker-image

**Comment by cmoralesmx** [comment]
Hi, the docs currently have an alert paragraph in [Lambda Container Images](https://docs.localstack.cloud/aws/lambda/#lambda-container-images) stating `bash` and `python 2/3` must be installed inside the container image.

What is the preferred course of action here, should I mention the failure and the error in this alert box?

**Comment by Smartmind12** [comment]
@HarshCasper Kindly assign this issue to me and i have a PR ready for it!
