### ISSUE TITLE
Add documentation - CI credits / CI workflow 

### ISSUE THREAD

**Issue by MarcelStranak** [localstack/docs#256]
Add details about CI credits
- what are CI credits
- how to use them 
- where to find how many were used
- how to increase the limits
...

**Comment by ojninja16** [comment]
hi @MarcelStranak , I would like to work on this....

**Comment by HarshCasper** [comment]
Hi @vikramadityasinghs — Happy to have you work on this :) 

Can you please fork this repository and set the documentation website on your local machine? I can help you consolidate the information and put it on a particular page here.

**Comment by vikramadityasinghs** [comment]
hey @HarshCasper  i'll start with forking the repo and setting up the website.

it'll be a great help if I could have a direction on what data is to be updated.

**Comment by vikramadityasinghs** [comment]
hey @HarshCasper ive set up the website on my local machine, it'll be helpful if i could get a direction on the information to be put on the page
