### ISSUE TITLE
Add _custom_id_ to ApiGateway docs

### ISSUE THREAD

**Issue by MarcelStranak** [localstack/docs#282]
Mention `_custom_id_` in the [API Gateway V2](https://docs.localstack.cloud/aws/apigatewayv2/) 
Based on [customer communication](https://localstack-community.slack.com/archives/C044YN380SZ)
[support sample](https://github.com/localstack/support-samples/tree/e5eaf09aaab762f200071d1528e487b3452b9d53/support_awehrung_u02kabl7bev) with a use case.
```
$ awslocal apigatewayv2 create-api --name=my-api --protocol-type=HTTP --tags="_custom_id_=my-api"                                                                                                                               
{
    "ApiEndpoint": "my-api.execute-api.localhost.localstack.cloud:4566",
    "ApiId": "my-api",
    "Name": "my-api",
    "ProtocolType": "HTTP",
    "Tags": {
        "_custom_id_": "my-api"
    }
}
```

**Comment by Alcadeus0** [comment]
hi, i'd like to work on this

**Comment by HarshCasper** [comment]
Hi @Alcadeus0 — Please let me know if you need any help with this :)

**Comment by Smartmind12** [comment]
@HarshCasper Is there anything else that needs to be updated here or is it duplicate of the previous issue??
