### ISSUE TITLE
Improve Documentation [ configuration.md ]

### ISSUE THREAD

**Issue by kaustav202** [localstack/docs#301]
The current configuration.md file has a lot of spelling mistakes, grammatical errors as well as contextual errors. All of these somewhat reduce the readability of the doc.

https://github.com/localstack/docs/blob/main/content/en/localstack/configuration.md

**Comment by kaustav202** [comment]
Can I work on this?

**Comment by thrau** [comment]
yes thank you @kaustav202 !
