### ISSUE TITLE
Fix display of "Exo" font

### ISSUE THREAD

**Issue by silv-io** [localstack/docs#303]
The ["Exo"](https://fonts.google.com/specimen/Exo) font is not loaded correctly for all users. See the screenshot below for how it looks when it is not loaded.

![image](https://user-images.githubusercontent.com/13120099/195806901-7b57fe53-e1f1-4181-a290-42579471d312.png)

**Comment by hannesfant** [comment]
This seems to be happening on at least safari on mac os for me. Mind if I jump on this?

**Comment by Bisht13** [comment]
Picking up this

**Comment by Bisht13** [comment]
PR opened, @silv-io please review 😃

**Comment by silv-io** [comment]
@Bisht13 thanks for the contribution. It's merged now!
