### ISSUE TITLE
Add feedback option for users

### ISSUE THREAD

**Issue by MarcelStranak** [localstack/docs#309]
Add Feedback option to LocalStack documentation pages.

As an example, we can use Feedback option similar to [AWS documentation](https://docs.aws.amazon.com/athena/latest/ug/what-is.html) with [Feedback form](https://docs-feedback.aws.amazon.com/feedback.jsp?hidden_service_name=Athena&topic_url=https://docs.aws.amazon.com/en_us/athena/latest/ug/what-is.html).

![image](https://user-images.githubusercontent.com/97876429/196621574-c1c06411-b20c-43a4-9549-b3ef82457b3f.png)
![image](https://user-images.githubusercontent.com/97876429/196621601-2e8f0433-05d8-4d90-b086-367c0085c3fc.png)
![image](https://user-images.githubusercontent.com/97876429/196621634-af7d0030-94b4-466f-bec7-017e0f053235.png)

**Comment by HarshCasper** [comment]
This is now shipped as:

![image](https://github.com/localstack/docs/assets/47351025/b8791326-3c0e-42d9-a219-fe1879240fdf)
