### ISSUE TITLE
cannot start localstack

### ISSUE THREAD

**Issue by David-orovs** [localstack/docs#314]
i keep running into this error when I run `docker run --rm -it -p 4566:4566 -p 4510-4559:4510-4559 localstack/localstack`   
 docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.

**Comment by HarshCasper** [comment]
Hi @David-orovs — I believe that you don't have Docker installed or you are running Docker. Can you please check the status of Docker on your local machine?

**Comment by HarshCasper** [comment]
Hi @David-orovs — I am closing this issue, since I don't believe that its a LocalStack issue. Please let me know if you need further help with this.
