### ISSUE TITLE
Quick start Guide Not working 

### ISSUE THREAD

**Issue by Eli3po** [localstack/docs#462]
I tried to follow the quick start guide and I got to the point when I need to run
`npm run web`
but there is no such script in `package.json` file of the project: 
<img width="306" alt="Screenshot 2023-02-02 at 19 09 32" src="https://user-images.githubusercontent.com/110763007/216393878-03a1a4a6-485c-4a88-9b97-0d6abfed9428.png">

Am I missing something?

**Comment by lakkeger** [comment]
Hi @Eli3po!
It seems at the time the documentation might had been outdated, apologies for that. As I was looking into this issue I checked the docs and the relevant repo as well and they are up-to-date now and the mentioned `npm run web` had been removed.
I'm closing this issue now, but if you experience any other issues, please do not hesitate to contact us.
