### ISSUE TITLE
AWS: Amplify

### ISSUE THREAD

**Issue by whummer** [localstack/docs#50]
In the docs for AWS Amplify, we should ideally cover these points:

* Basic API endpoints: Applications, branches, environments, ...
* Using the `amplifylocal` CLI to create and deploy Amplify apps: https://github.com/localstack/amplify-js-local
* Using the Amplify JS libs in a Web UI - e.g., to use the auto-generated Login UIs from Amplify with the local APIs. Some details here as a starting point: https://github.com/localstack/amplify-js-local#using-the-library-in-your-es6-javascript-code-eg-react-frontend
* We can also reference this sample app which uses Amplify (among other APIs): https://github.com/localstack/localstack-pro-samples/tree/master/aws-sam-amplify-lambda-webapp

**Comment by lakkeger** [comment]
@HarshCasper @whummer is this something that had been added already?
