### ISSUE TITLE
[Improvement] SQS SNS subscription

### ISSUE THREAD

**Issue by Lewiscowles1986** [localstack/docs#511]
Share localstack SNS subscription via SQS, or point to AWS docs page.

I am willing to make this contribution (please signpost me)

**Comment by thrau** [comment]
hey @Lewiscowles1986, do you mean you would like instructions in the docs on how to subscribe an SQS queue to an SNS topic?
i think that would be an excellent addition! if we can point to AWS docs that work against localstack, then that may be the easiest.

we'd appreciate the contribution

**Comment by Lewiscowles1986** [comment]
Thanks @thrau. The AWS docs I am aware of are less clear about that; but I've submitted a draft, which I hope gives us something to iterate upon, or submit.
