### ISSUE TITLE
Add description / troubleshooting guide for using local SSL certs

### ISSUE THREAD

**Issue by whummer** [localstack/docs#60]
Got this hint from a customer, regarding the local SSL certs we're using for the `*.localhost.localstack.cloud` endpoints - might be worth adding a few hints to the documentation..

<img width="809" alt="image" src="https://user-images.githubusercontent.com/2807888/136774571-f9beef16-11db-402b-b3cf-b7ab917480ae.png">

**Comment by ankitagit11** [comment]
I want to work on this issue. Please assign it to me.

**Comment by lakkeger** [comment]
@ankitagit11 , have this been added?
