### ISSUE TITLE
make deploy command fails

### ISSUE THREAD

**Issue by atiurmalasetti** [localstack/docs#612]
✖ Stack demo1 failed to deploy (8s)
Environment: darwin, node 18.10.0, framework 3.29.0 (local) 3.30.1v (global), plugin 6.2.3, SDK 4.3.2
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
CREATE_FAILED: demo1 (AWS::CloudFormation::Stack)
undefined

View the full error: https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aus-east-1%3A000000000000%3Astack%2Fdemo1%2F11dffad8

1 deprecation found: run 'serverless doctor' for more details
make: *** [deploy] Error 1

**Comment by HarshCasper** [comment]
We have shipped a new Quickstart guide here — https://docs.localstack.cloud/getting-started/quickstart/
