### ISSUE TITLE
Make Lambda layer docs a little simpler

### ISSUE THREAD

**Issue by lizconlan** [localstack/docs#617]
Having managed to get myself a bit lost trying to use a freshly created Lambda layer to a create-function command, it feels like it would be simpler to modify the jq query to fetch the `LayerVersionArn` (the `LayerArn` with the version number already appended) rather than manually adding it as part of the call to `lambda create-function`.

It's also a bit easier to follow what's happening across 2 different commands.

**Comment by ackdav** [comment]
Hi @lizconlan - I'm closing this due to the linked PR already having been merged (appreciate your input! :rocket:). If you feel like there's still room for improvements, feel free to open a new one :smiley: thx!
