### ISSUE TITLE
Amazon API Gateway

### ISSUE THREAD

**Issue by lorandlvarga** [localstack/docs#640]
https://docs.localstack.cloud/user-guide/aws/apigateway/#add-a-method-and-integration

I think instead of POST it should be GET in the example.
`awslocal apigateway put-integration \
  --rest-api-id <REST_API_ID> \
  --resource-id <RESOURCE_ID> \
  --http-method GET \
  --type AWS_PROXY \
  --integration-http-method POST \
  --uri arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:000000000000:function:apigw-lambda/invocations \
  --passthrough-behavior WHEN_NO_MATCH`
  
  I believe the --uri does not need to containd that date string right?
  
  Also, --path-part "{somethingId}" in the examples is not very explicit for new comers.

**Comment by HarshCasper** [comment]
We have shipped a new APIGW guide — https://docs.localstack.cloud/user-guide/aws/apigateway/

Please let us know if you are facing any further troubles. Thank You!
