### ISSUE TITLE
Quickstart

### ISSUE THREAD

**Issue by kalnida1** [localstack/docs#642]
Please, add information about `make`, as how to install it, is it GNU make or some other thing?

**Comment by thrau** [comment]
Hi @kalnida1. We use just regular Make which is a standard tool in most developer environments. However make is really only used as internal developer tool, it should not be something LocalStack users need to worry about. Could you point to the particular piece in the documentation where you thought that information is missing?

**Comment by thrau** [comment]
Without further input, it's not clear what we can improve, so closing this for now. Please re-open if you can provide more information
