### ISSUE TITLE
AWS ApiGateway Custom ID via tags

### ISSUE THREAD

**Issue by dominikschubert** [localstack/docs#65]
See https://github.com/localstack/localstack/blob/3f9476f3025ba803853dfd091be4c2b6cffc8443/README.md?plain=1#L538 and https://github.com/localstack/localstack/issues/3868#issuecomment-945865161

**Comment by Smartmind12** [comment]
@dominikschubert Can you assign this issue to me...thanks!

**Comment by Smartmind12** [comment]
@dominikschubert I am not being able to find the Readme doc after forking the repo because the  https://github.com/localstack/localstack/blob/3f9476f3025ba803853dfd091be4c2b6cffc8443/README.md?plain=1#L538 is on a local branch which cannot be accessed on forking. 

So can you show me the path so that i can work on it?

**Comment by HarshCasper** [comment]
Hi @Smartmind12 — That's an outdated reference to the `README.md` which you are looking at. 

You can make changes over here:

- https://github.com/localstack/docs/blob/main/content/en/aws/apigatewayv2/index.md

You just need to document this [feature](https://github.com/localstack/localstack/issues/3868#issuecomment-945865161) over there.

**Comment by Smartmind12** [comment]
> Hi @Smartmind12 — That's an outdated reference to the `README.md` which you are looking at.
> 
> You can make changes over here:
> 
> * https://github.com/localstack/docs/blob/main/content/en/aws/apigatewayv2/index.md
> 
> You just need to document this [feature](https://github.com/localstack/localstack/issues/3868#issuecomment-945865161) over there.

Thanks alot @HarshCasper ! I have made the changes for the same!
