### ISSUE TITLE
AWS CDK: Document needs to be updated

### ISSUE THREAD

**Issue by rahulmlokurte** [localstack/docs#650]
When we run `cdklocal deploy` following the example given on https://docs.localstack.cloud/user-guide/integrations/aws-cdk/#example , we get the below error.

```json
Deployment failed: Error: TestStack: SSM parameter /cdk-bootstrap/hnb659fds/version not found. Has the environment been bootstrapped? Please run 'cdk bootstrap' (see https://docs.aws.amazon.com/cdk/latest/guide/bootstrapping.html)
```

**Comment by dominikschubert** [comment]
Resolved in https://github.com/localstack/docs/pull/651. Thanks again for reporting & resolving the issue :+1:
