### ISSUE TITLE
Testcontainers

### ISSUE THREAD

**Issue by calvernaz** [localstack/docs#658]
The version should be the only thing passed to the container object. 
```
LocalStackContainer localstack = new LocalStackContainer("localstack/localstack:2.0.0");
```

It should look like this,

```
LocalStackContainer localstack = new LocalStackContainer("2.0.0");
```

**Comment by eddumelendez** [comment]
Hi, the recommended way is to pass the full image name. why? custom images based on localstack/localstack:2.1.0. But, I noticed it should ve DockerImageName.parse("localstack/localstack:2.1.0") instead

**Comment by eddumelendez** [comment]
I have just raised https://github.com/localstack/docs/pull/660

**Comment by eddumelendez** [comment]
#660 has been merged. This issue can be closed.
