### ISSUE TITLE
Concurrency in LocalStack (e.g. Lambda invoke)

### ISSUE THREAD

**Issue by dominikschubert** [localstack/docs#66]
Document if/how Lambdas, Rest APIs, etc. handle concurrent executions and if there are any specific limitations depending on the Lambda executor in use (local/docker/docker-reuse). Should probably be added to https://docs.localstack.cloud/localstack/lambda-executors/

Also answer https://github.com/localstack/localstack/issues/3583 or point the user to the new content.

**Comment by whummer** [comment]
Great point. 👍 Also related to this one: https://github.com/localstack/localstack/issues/3636

**Comment by lakkeger** [comment]
@dominikschubert @whummer , have this been added to the docs?
