### ISSUE TITLE
Can't start localstack when following installation doc.

### ISSUE THREAD

**Issue by cmccoy98** [localstack/docs#661]
When trying to run `localstack start` and following the Linux Installation docs [here](https://docs.localstack.cloud/getting-started/installation/#localstack-cli). The following error is thrown and the application crashes.

`[   MainThread] localstack.utils.function: error calling function save: [Errno 13] Permission denied: '/var/lib/localstack'`

**Comment by HarshCasper** [comment]
Hi — Can you please try out the new `localstack` CLI and dev experience with LocalStack 3.0 release? If you face further issues, please create a new issue here: https://github.com/localstack/localstack/issues/new/choose
