### ISSUE TITLE
Make it clear that persistence is a Pro feature

### ISSUE THREAD

**Issue by trb** [localstack/docs#662]
Put a header or icon or anything attention-drawing on this page: https://docs.localstack.cloud/references/persistence-mechanism/

I spent a couple of hours trying to figure out why persistence isn't working anymore, only to find out from a git issue that it's now a Pro feature and that it's supposedly mentioned on the persistence page. Yeah - as a random sentence in the introduction.

Makes me feel like you want to hide the fact that persistence if for-pay now. Now sure why, but it did waste a bunch of my time.

**Comment by HarshCasper** [comment]
We are reworking our docs here — https://github.com/localstack/docs/pull/1001

We will take your feedback into consideration.
