### ISSUE TITLE
Docs enhancement: Adding a copy button in the command sections

### ISSUE THREAD

**Issue by aminblm** [localstack/docs#70]
Adding a copy button in the command sections would allow faster copy-pasta.

**Comment by ankitagit11** [comment]
I want to work on this issue. Please assign it to me.

**Comment by lukqw** [comment]
@ankitagit11 are you still interested in this issue?

**Comment by lukqw** [comment]
closing since this was already implemented in https://github.com/localstack/docs/pull/719
