### ISSUE TITLE
Broken back ticks and incorrect usage strings

### ISSUE THREAD

**Issue by chrisdurand-RL** [localstack/docs#704]
On https://docs.localstack.cloud/user-guide/tools/cloud-pods/pods-cli/, the usage strings are showing how to run the cli from within the repository rather than the deployed binary. 

It should show:
```
Usage: localstack [OPTIONS] COMMAND [ARGS]...
```

Additionally, there are broken code annotations later on the [list](https://docs.localstack.cloud/user-guide/tools/cloud-pods/pods-cli/#list) section.

**Comment by thevinitgupta** [comment]
I would love to work on this
