### ISSUE TITLE
pip install awscli-local[ver1]  command returns zsh: no matches found: awscli-local[ver1]

### ISSUE THREAD

**Issue by boguth** [localstack/docs#727]
I am unfamiliar with pip extras and am unclear one what ver1 is supposed to be. When I copy it and paste it into my terminal, I get an error. Some context in the docs would help me better understand what ver1 is, why I am installing it, and why I am might get an error. Thank you.

**Comment by thrau** [comment]
hey @boguth , this is a zsh peculiarity, you need to add quotes when using brackets in a string.

```
pip install 'awscli-local[ver1]'
```

should work

**Comment by lakkeger** [comment]
Hi. We just wanted to follow up on our last message to see whether your issue has been resolved. Were you able to get it working with the instructions we provided? We would appreciate your feedback!

**Comment by boguth** [comment]
Yes! It was resolved. Thank you for following up @lakkeger
