### ISSUE TITLE
awful quickstart experience

### ISSUE THREAD

**Issue by yukilab2** [localstack/docs#732]
cannot do this in 5minutes
- I first need Pro feature, so I subscribed trial one. not mentioned in quickstart
- sign up requested in quickstart take me long time; I logged in with github account and don't know user and password. To find and set correctly , I wasted time for several tries just to start your application and that is nothing worth to me except I feed this is bad UX.
- container:  although doc tell you are using docker container, I installed with localstack wth brew and nothing know about where container image came.  After I started QUICKSTART, I found i need to remove above installation and need to pull PRO version container. (I don't know how I can use brew in this case, so I do docker pull -- this also not mentioned in your quick start)

If this kind of UX I'm experiencing... I won't subscribe this. This is very sad since I pretty much hope I use this local tool with very good experience than cloud one, AWS.

**Comment by thrau** [comment]
thanks for the feedback @yukilab2. we know the quickstart experience needs improvement, and we're currently actively working on making this better, especially when you use the pro version. you'll see some changes in the upcoming months which should address all the points you mentioned!

If you're interested in getting a preview and giving feedback to help shape the experience, please feel free to sign up to the localstack insiders program here: https://localstack.cloud/insiders/
