### ISSUE TITLE
What is the image uri?

### ISSUE THREAD

**Issue by danielcamargo** [localstack/docs#781]
I am trying to create a task definition using Terraform, and I don't know how to inform the image URI.

```tf
resource "aws_ecs_task_definition" "my_task" {
    family                   = local.app_name
    network_mode             = "awsvpc"
    execution_role_arn       = aws_iam_role.execution_role.arn
    task_role_arn            = aws_iam_role.execution_role.arn
    requires_compatibilities = ["FARGATE"]
    cpu                      = var.cpu
    memory                   = var.memory
    container_definitions    = jsonencode([
        {
            name : local.app_name,
            image : var.DOCKER_IMAGE,
```

**Comment by lakkeger** [comment]
Hi @danielcamargo,
Thank you for your patience. To give a simple static example you can define a task the following way:
```
resource "aws_ecs_task_definition" "hello_world" {
  family                   = "hello-world-app"
  network_mode             = "awsvpc"
  requires_compatibilities = ["FARGATE"]
  cpu                      = 1024
  memory                   = 2048

  container_definitions = <<DEFINITION
[
  {
    "image": "registry.gitlab.com/architect-io/artifacts/nodejs-hello-world:latest",
    "cpu": 1024,
    "memory": 2048,
    "name": "hello-world-app",
    "networkMode": "awsvpc",
    "portMappings": [
      {
        "containerPort": 3000,
        "hostPort": 3000
      }
    ]
  }
]
DEFINITION
}
```
In your example the `var.DOCKER_IMAGE` should contain something like this string:
`registry.gitlab.com/architect-io/artifacts/nodejs-hello-world:latest`

For additional information the official documentation from AWS can give a better overview:
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_image

Please, let us know if this has helped and do not hesitate to contact us if you have any further questions.
