### ISSUE TITLE
Improve documentation on browser compatibility with dashboard

### ISSUE THREAD

**Issue by thrau** [localstack/docs#79]
Recently people have been reporting issues with the app and brave browser. We could improve the documentation here: https://docs.localstack.cloud/tools/analytics-dashboard/

**Comment by dominikschubert** [comment]
just some additional info

Brave blocks requests to localhost by default but it can be manually enabled via the site settings => Insecure Content => Allow

**Comment by iamrajiv** [comment]
@thrau Can I work on this?

**Comment by thrau** [comment]
hi @iamrajiv yes please feel free to pick it up
