### ISSUE TITLE
Missing configuration section for SES documentation

### ISSUE THREAD

**Issue by hkrynicki** [localstack/docs#83]
Just as in the title, the `Configuration section`  hyperlink redirects to nothing in https://docs.localstack.cloud/aws/ses/

**Comment by iamrajiv** [comment]
Hi @hkrynicki should I remove the link from the `Configuration section` or is there a dedicated link for it?

**Comment by hkrynicki** [comment]
Hi @iamrajiv I don't know if there is a dedicated link for the configuration section, but there definitely should be. This piece of documentation is clearly missing.  I've created this issue because I don't know how to configure SMTP server for SES.

**Comment by HarshCasper** [comment]
Hi — We have reworked our docs and now the `Configuration` guide links to https://docs.localstack.cloud/references/configuration/#emails
