### ISSUE TITLE
Custom IDs generating random IDs in (KMS)

### ISSUE THREAD

**Issue by tiago-malveira-tr** [localstack/docs#832]
Hi guys,

Trying to figure out how to create a custom id for a key as suggested by the documentation [Custom IDs for KMS keys via tags](https://docs.localstack.cloud/user-guide/aws/kms/#custom-ids-for-kms-keys-via-tags) but still could not make it work.

When I use the sample command provided by the docs i.e. `awslocal kms create-key --tags '[{"TagKey":"_custom_id_","TagValue":"00000000-0000-0000-0000-000000000001"}]'` I always get a random key arn.

I'm simply executing the command in  the container's terminal. Is there anything I'm missing?

**Comment by lakkeger** [comment]
Hi! We just wanted to follow up to see whether your issue has been resolved. Were you able to get it working with the latest version of LocalStack? We would appreciate your feedback!

**Comment by adase11** [comment]
I'm observing the same behavior as @tiago-malveira-tr originally reported using version `3.0.2` :

```shell
$ awslocal kms create-key --tags '[{"TagKey":"_custom_id_","TagValue":"00000000-0000-0000-0000-000000000001"}]'
{
    "KeyMetadata": {
        "AWSAccountId": "000000000000",
        "KeyId": "36b074f6-8969-4b8a-bc53-b52cba9b88de",
        "Arn": "arn:aws:kms:us-east-1:000000000000:key/36b074f6-8969-4b8a-bc53-b52cba9b88de",
        "CreationDate": "2024-01-16T14:17:37.070792-05:00",
        "Enabled": true,
        "Description": "",
        "KeyUsage": "ENCRYPT_DECRYPT",
        "KeyState": "Enabled",
        "Origin": "AWS_KMS",
        "KeyManager": "CUSTOMER",
        "CustomerMasterKeySpec": "SYMMETRIC_DEFAULT",
        "KeySpec": "SYMMETRIC_DEFAULT",
        "EncryptionAlgorithms": [
            "SYMMETRIC_DEFAULT"
        ],
        "MultiRegion": false
    }
}

$ localstack --version
3.0.2

```

**Comment by MarcelStranak** [comment]
Hi @adase11, I am unable to reproduce the issue in the `latest` version of LocalStack.
Please pull the latest docker image and give it a go. (`docker pull localstack/localstack:latest`)
```sh
awslocal kms create-key --tags '[{\"TagKey\":\"_custom_id_\",\"TagValue\":\"00000000-0000-0000-0000-000000000001\"}]'
{
    "KeyMetadata": {
        "AWSAccountId": "000000000000",
        "KeyId": "00000000-0000-0000-0000-000000000001",
        "Arn": "arn:aws:kms:us-east-1:000000000000:key/00000000-0000-0000-0000-000000000001",
        "CreationDate": 1705483489.607959,
        "Enabled": true,
        "Description": "",
        "KeyUsage": "ENCRYPT_DECRYPT",
        "KeyState": "Enabled",
        "Origin": "AWS_KMS",
        "KeyManager": "CUSTOMER",
        "CustomerMasterKeySpec": "SYMMETRIC_DEFAULT",
        "KeySpec": "SYMMETRIC_DEFAULT",
        "EncryptionAlgorithms": [
            "SYMMETRIC_DEFAULT"
        ],
        "MultiRegion": false
    }
}
```

**Comment by adase11** [comment]
Thanks @MarcelStranak I pulled the latest and that resolved things. Works just fine now
