### ISSUE TITLE
Add Open Graph image

### ISSUE THREAD

**Issue by iamrajiv** [localstack/docs#87]
## Description

The Open Graph images are not generated when we share https://docs.localstack.cloud/ over social media.

![Screenshot 2021-12-14 at 9 14 39 AM](https://user-images.githubusercontent.com/42106787/145929386-e8d5f107-04e6-43f0-b97b-0c539920a316.jpg)

## References

- Use https://developers.facebook.com/tools/debug/ to validate results for Facebook.
- Use https://www.linkedin.com/post-inspector/ to validate results for LinkedIn.
- Use https://cards-dev.twitter.com/validator to validate results for Twitter.

**Comment by iamrajiv** [comment]
@whummer @thrau

**Comment by iamrajiv** [comment]
@thrau @whummer

**Comment by HarshCasper** [comment]
Hi @iamrajiv 👋 

Would you like to work on it? I have assigned you the issue, but feel free to issue if there is something else on priority 😄

**Comment by Bisht13** [comment]
Taking this up ✨
