### ISSUE TITLE
error script.py

### ISSUE THREAD

**Issue by deinerariza** [localstack/docs#901]
Hello,

I've followed the documentation 'Kinesis Data Analytics', however this happened:

botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "http://localhost.localstack.cloud:4566/"

I don't know what endpoint_url means.

On the other hand, it is a great idea a SQL example to complete the Kinesis Data Analytics functions.

Thanks

**Comment by HarshCasper** [comment]
Hi @deinerariza — Is LocalStack running on your local machine? Unless the LocalStack container is running on your host machine and `http://localhost.localstack.cloud:4566/` is accessible, you won't be able to run the sample.
