### ISSUE TITLE
Quick start assumes you have something called pip

### ISSUE THREAD

**Issue by paulhickman-ec** [localstack/docs#910]
In your quickstart the next step after downloading the CLI and running the docker image seems to be to use awslocal

````
if you have the awslocal [CLI installed](https://github.com/localstack/awscli-local) (via pip install awscli-local), you can run the following command to see the archive results in the local S3 bucket:
````
However there is nothing to tell the user what pip is or where to get it. I think its assuming the user is a python developer.

**Comment by lakkeger** [comment]
Hi @paulhickman-ec,
Thank you for your valuable feedback and pointing out hard to understand parts of the article. We strive to make it more user-friendly as following these instructions is the first interaction for many with Localstack.

If you have any further questions or feedbacks please do not hesitate to get in touch with us.

**Comment by HarshCasper** [comment]
A new quickstart is in development here — https://github.com/localstack/docs/pull/976
