### ISSUE TITLE
CDK for Terraform docs duplication/omission

### ISSUE THREAD

**Issue by cmclaughlin** [localstack/docs#959]
On this page https://docs.localstack.cloud/user-guide/integrations/cdk-for-terraform/

In the `localstack_config.py` example - this is listed twice in the AWS_CONFIG endpoints dictionary

```
"sts": "http://localhost:4566",
```

Although the "LocalStack & CDKTF" section provides a Python example, the "Quick Start" section only has Typescript. Consistency with both languages on the tutorial would be nice.

**Comment by lakkeger** [comment]
Hi @cmclaughlin,
Thanks for the reported issue and valuable insights. We've prepared a relevant PR (#962), hopefully it goes live soon.
